name: Construkt
main: com.github.razz0991.construkt.Construkt
version: ${project.version}
author: _Razz_
api-version: 1.15
commands:
   construkt:
      description: Enables or disables Construkt.
      usage: /construkt
      permission: construkt.command
      permission-message: You don't have permission to use Construkt!
      aliases: [ckt]
   construktundo:
      description: Undo a change made in Construkt.
      usage: /construcktundo
      permission: construkt.undo
      permission-message: You don't have permission to undo in Construkt!
      aliases: [cktundo, cktu]
   construktredo:
      description: Redo a change made in Construkt.
      usage: /construcktredo
      permission: construkt.redo
      permission-message: You don't have permission to redo in Construkt!
      aliases: [cktredo, cktr]
permissions:
   construkt.*:
      description: Gives full access to Construkt
      children:
         construkt.limited: true
         construkt.bypass_limits: true
   construkt.limited:
      description: Gives full access but still has block limits
      children:
         construkt.command: true
         construkt.undo: true
         construkt.redo: true
         construkt.mode.*: true
         construkt.shape.*: true
   construkt.command:
      description: Allows use of Construkt's commands
      default: op
   construkt.undo:
      description: Allows a player to use undo
      default: op
   construkt.mode.*:
      description: Allows all modes, place, break, and replace
      children:
         construkt.mode.place: true
         construkt.mode.break: true
         construkt.mode.replace: true
   construkt.mode.place:
      description: Allows placement mode
      default: op
   construkt.mode.break:
      description: Allows break mode
      default: op
   construkt.mode.replace:
      description: Allows replace mode
      default: op
   construkt.shape.*:
      description: Allows all shapes
      children:
         construkt.shape.cuboid: true
         construkt.shape.hollow_cuboid: true
         construkt.shape.overlay: true
         construkt.shape.sphere: true
         construkt.shape.terrain: true
   construkt.shape.cuboid:
      description: Allows use of the cuboid shape
      default: true
   construkt.shape.hollow_cuboid:
      description: Allows use of the hollow cuboid shape
      default: op
   construkt.shape.overlay:
      description: Allows use of the overlay shape
      default: op
   construkt.shape.sphere:
      description: Allows use of the sphere shape
      default: op
   construkt.shape.terrain:
      description: Allows use of the terrain shape
      default: op
   construkt.bypass_limits:
      description: Allows user to bypass area limitations
      default: op
 